apiRules:
- include:
    # Including the OmiyaGames.Global namespace
    uidRegex: ^OmiyaGames\.Global$
    type: Namespace
- include:
    # Including the OmiyaGames.Global.Editor namespace
    uidRegex: ^OmiyaGames\.Global\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace